### ISSUE TITLE
Draggable incompatibility with some drag 'n drop slides

### ISSUE THREAD

**Issue by azjgard** [azjgard/qa-helper-2#1]
When testing the slide with a reference ID of **AD12-105-Web18-5-1-08-1** while our extension is active, incorrect behavior occurs. The drag 'n drop functionality still works, but upon dragging the answers to the correct locations and clicking "Check Answers", no visual feedback appears and the "Next" arrow remains grayed out and unclickable.

**Comment by sottom** [comment]
Slide **AD12-102-Web04-2-1-11-1** also has the same issue.
"Gearset Theory and Failure Modes"

![image](https://user-images.githubusercontent.com/18564176/27549018-8e57d7aa-5a4f-11e7-8e87-396834c62012.png)

AD12-105-Web22-4-1-06-1 "Types of Temperature Sensors"

**Comment by azjgard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Text comparison via OCR](https://trello.com/c/ZIAahTXG/8-text-comparison-via-ocr)

**Comment by azjgard** [comment]
There was an issue with the jQuery library that the extension loads that was conflicting with the library that is already present in the slides. Additionally, there were class name conflicts. The new class name for the draggable templates generated by the extension is '.qa-ext_draggable' to avoid this.

Fixed [in this commit.](https://github.com/azjgard/qa-helper-2/commit/70e2035ee52187e82c2307daf1857a0c02bc71df)
